import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    body: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        paddingLeft: 16,
        paddingRight: 16,
        paddingTop: 16,
        backgroundColor: '#fff',
    },
    headerText: {
        fontSize: 22,
    },
    textSubscri: {
        fontSize: 13,
    },
    linerHeader: {
        marginTop: 10, 
        height: 40,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 10,
        paddingRight: 10,
    },
    scrollView: {
        width: '100%',
        paddingTop: 20,
    },
    buttonBack: {
        position: 'absolute',
        left: 4,
    },
    buttonSeting: {
        position: 'absolute',
        right: 4,
    },
    borderImage: {
        width: 150,
        height: 150,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
    },
    borderImageWite: {
        width: 145,
        height: 145,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
    },
    image: {
        width: 110,
        height: 110,
        borderRadius: 100,
    },
    textNameButton: {
        fontSize: 14,
        color: '#000',
    },
    textCounterButton: {
        fontSize: 15,
        color: '#000',
    },
    buttonSubscribers: {
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 20,
    },
    buttonSubscriptions: {
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 20,
    },
    linerSub: {
        marginTop: 16,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    minLiner: {
        marginTop: 30,
        width: '100%',
        paddingLeft: 4,
        paddingRight: 4,
        justifyContent: 'center',
        flexDirection: 'row',
    },
    textNameMin: {
        marginTop: 8,
        fontSize: 14,
        color: 'rgba(0, 0, 0, 1)',
    },
    textNameMinA: {
        marginTop: 8,
        fontSize: 14,
        color: 'rgba(0, 0, 0, 0.62)',
    },
    buttonNearest: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    buttonPlans: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    buttonArchive: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    ScrollView: {
        marginTop: 10,
        width: '100%',

    },
    textMin: {
        marginTop: 50,
        width: '100%',
        textAlign: 'center',
    },
    linerAvatar: {
        width: '100%',
        alignItems: 'center',
    },
    buttonSend: {
        zIndex: 3,
        position: 'absolute',
        bottom: 25,
        right: 25,
        backgroundColor: 'rgba(255, 255, 255, 1)',
        borderRadius: 100,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ rotate: '-20deg' }],
    },
    buttonAddAvatar: {
        position: 'absolute',
        left: 16,
        bottom: 6,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconAdd: {
        width: 25,
        height: 25,
    },
    cameraPanel: {
        width: '100%',
        height: 200,
        position: 'absolute',
        bottom: 0,
    },
    menuPanel: {
        width: '100%',
        height: 250,
        position: 'absolute',
        bottom: 0,
    },
    bacdoor: {
        top: 0,
        position: 'absolute',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        flex: 1,
        width: '100%',
        height: '100%',
    },
    dialogView: {
        width: '100%',
        paddingLeft: 10,   
        paddingRight: 10,
    },
    dialogTypePhoto: {
        width: '100%',
        height: 120,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
    },
    dialogTypeMenu: {
        width: '100%',
        height: 160,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
    },
    buttonNoDialog: {
        marginTop: 10,
        marginBottom: 10,
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
    },
    buttonPhone: {
        width: '100%',
        height: '50%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonMenu: {
        width: '100%',
        height: '33%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textConstButtonPhoto: {
        color: '#2D65EF',
    },
    textConstButtonBloc: {
        color: 'red',
    },
    hrPhone: {
        width: '100%',
        height: 1,
        backgroundColor: '#E9E9E9',
    },
});