import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    body: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        paddingLeft: 16,
        paddingRight: 16,
        paddingTop: Platform.OS == "ios" ? 25 : 16,
        backgroundColor: '#fff',
    },
    headerText: {
        fontSize: 22,
    },
    linerHeader: {
        marginTop: 10, 
        height: 40,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 10,
        paddingRight: 10,
    },
    scrollView: {
        width: '100%',
        paddingTop: 20,
    },
    buttonBack: {
        position: 'absolute',
        left: 4,
    },
    buttonSeting: {
        position: 'absolute',
        right: 4,
    },
    borderImage: {
        width: 150,
        height: 150,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
    },
    borderImageWite: {
        width: 145,
        height: 145,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 100,
    },
    image: {
        width: 110,
        height: 110,
        borderRadius: 100,
    },
    textNameButton: {
        fontSize: 14,
        color: '#000',
    },
    textCounterButton: {
        fontSize: 15,
        color: '#000',
    },
    buttonSubscribers: {
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 20,
    },
    buttonSubscriptions: {
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 20,
    },
    linerSub: {
        marginTop: 16,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    minLiner: {
        marginTop: 30,
        width: '100%',
        paddingLeft: 4,
        paddingRight: 4,
        justifyContent: 'center',
        flexDirection: 'row',
    },
    textNameMin: {
        marginTop: 8,
        fontSize: 14,
        color: 'rgba(0, 0, 0, 0.62)',
    },
    buttonNearest: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    buttonPlans: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    buttonArchive: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '33.33%',
    },
    ScrollView: {
        marginTop: 10,
        width: '100%',
        paddingLeft: 4,
        paddingRight: 4,
    },
    linerAvatar: {
        marginTop: 20,
        alignItems: 'center',
    },
    textMinData: {
        marginTop: 15,
        fontSize: 14,
        width: '100%',
        textAlign: 'center',
    },
    panelData: {
        width: '100%',
        marginTop: 10,
        marginBottom: 10,
    },
    textConstAcaunt: {
        marginLeft: 22,
        fontSize: 15,
        color: '#949494',
    },
    borderItemData: {
        height: 53,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 40,
        padding: 3,
        marginTop: 8,
    },
    borderItemDataWite: {
        width: '100%',
        height: '100%',
        backgroundColor: '#fff',
        borderRadius: 39,
        paddingTop: 12,
        paddingBottom: 12,
        paddingLeft: 16,
        paddingRight: 16,
    },
    textConstAnceta: {
        fontSize: 16,
        color: '#000',
    },
    linerHeaderItemDataNema: {
        flexDirection: 'row',
    },
    linerHeaderItemDataNema: {
        justifyContent: 'center',
    },
    iconItemData: {
        position: 'absolute',
        right: 0,
    },
    textConstInput: {
        marginTop: 15,
        marginLeft: 8,
        color: '#949494',
        fontSize: 12,
    },
    input: {
        width: '100%',   
        paddingLeft: 10,
        paddingRight: 10,
        height: 42,
        backgroundColor: '#F9F9F9',
        borderRadius: 15,
        borderColor: '#C4C4C4',
        borderWidth: 1,
        textAlignVertical: "top"
    },
    linerDataItemButton: {
        width: '100%',
        paddingLeft: 60,
        paddingRight: 60,
    },
    dataItemButton: {
        marginTop: 20,
        width: '100%',
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: 'rgba(130, 83, 216, 1)',
        // backgroundColor: 'rgba(193, 10, 203, 1)',
        height: 32,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textItemDataButton: {
        fontSize: 16,
        color: 'rgba(130, 83, 216, 1)',
    },
    buttonLogout: {
        marginTop: 10,
        marginBottom: 15,
    },
    textButtonLogout: {
        width: '100%',
        textAlign: 'center',
        color: 'rgba(130, 83, 216, 1)',
    },
    buttonAddAvatar: {
        position: 'absolute',
        left: 12,
        bottom: 0,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    iconAdd: {
        width: 25,
        height: 25,
    },
    dialogView: {
        width: '100%',
        paddingLeft: 10,   
        paddingRight: 10,
    },
    dialogTypePhoto: {
        width: '100%',
        height: 120,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
    },
    buttonNoDialog: {
        marginTop: 10,
        marginBottom: 10,
        width: '100%',
        height: 60,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
    },
    buttonPhone: {
        width: '100%',
        height: '50%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textConstButtonPhoto: {
        color: '#2D65EF',
    },
    hrPhone: {
        width: '100%',
        height: 1,
        backgroundColor: '#E9E9E9',
    },
});